hpc <- read.table("household_power_consumption.txt", head = TRUE, sep = ";")
library(lubridate)
hpc$Date <- dmy(hpc$Date)
hpc$Time <- hms(hpc$Time)
hpc_2days <- subset(hpc, Date == ymd("2007-02-01") | Date == ymd("2007-02-02"))
GAP <- as.numeric(as.character(hpc_2days$Global_active_power))
png(filename = "plot1.png")
hist(GAP, xlab = "Global Active Power (kilowatts)", ylab = "Frequency", main = "Global Active Power", col = "red")
dev.off()
